import { db } from '../lib/firebase';
import { doc, setDoc, serverTimestamp } from 'firebase/firestore';

export enum BIEventType {
  SALE_COMPLETED = 'SALE_COMPLETED',
  SALE_BLOCKED_ZERO_STOCK = 'SALE_BLOCKED_ZERO_STOCK',
  SHIFT_OPENED = 'SHIFT_OPENED',
  SHIFT_CLOSED = 'SHIFT_CLOSED',
  CASH_VARIANCE_FOUND = 'CASH_VARIANCE_FOUND',
  STOCKTAKE_SUBMITTED = 'STOCKTAKE_SUBMITTED',
  STOCK_ADJUSTMENT_REQUESTED = 'STOCK_ADJUSTMENT_REQUESTED',
  COGS_RESERVED = 'COGS_RESERVED',
  COGS_USED = 'COGS_USED',
  COGS_MISUSE_ATTEMPT = 'COGS_MISUSE_ATTEMPT',
  GOODS_RECEIVED = 'GOODS_RECEIVED',
  PRICE_OVERRIDE_REQUESTED = 'PRICE_OVERRIDE_REQUESTED',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUND_APPROVED = 'REFUND_APPROVED',
  DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED',
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
  FAILED_TERMINAL_LOGIN = 'FAILED_TERMINAL_LOGIN',
  CASH_BANK_MOVEMENT = 'CASH_BANK_MOVEMENT',
  LOW_STOCK_REMINDER = 'LOW_STOCK_REMINDER',
  REORDER_REQUESTED = 'REORDER_REQUESTED',
  REORDER_WITH_NO_SALES_SINCE_LAST_REQUEST = 'REORDER_WITH_NO_SALES_SINCE_LAST_REQUEST',
  MAJOR_STOCKTAKE_RECOMMENDED = 'MAJOR_STOCKTAKE_RECOMMENDED',
  SALES_DISCOUNT_APPLIED = 'SALES_DISCOUNT_APPLIED',
  APP_ACTIVITY_LOGGED = 'APP_ACTIVITY_LOGGED',
  WHATSAPP_LEAD_RECEIVED = 'WHATSAPP_LEAD_RECEIVED',
  STOCK_TRANSFER_REQUESTED = 'STOCK_TRANSFER_REQUESTED',
  STOCK_TRANSFER_APPROVED = 'STOCK_TRANSFER_APPROVED',
  STOCK_TRANSFER_COMPLETED = 'STOCK_TRANSFER_COMPLETED',
  STOCK_HEALTH_UPDATED = 'STOCK_HEALTH_UPDATED',
  RETURN_CUSTOMER_DETECTED = 'RETURN_CUSTOMER_DETECTED',
  OPEX_LEAKAGE_DETECTED = 'OPEX_LEAKAGE_DETECTED',
  UNCLASSIFIED_OPEX_DETECTED = 'UNCLASSIFIED_OPEX_DETECTED',
  NON_MOVING_STOCK_DETECTED = 'NON_MOVING_STOCK_DETECTED',
  STOCK_DISPOSAL_RECOMMENDED = 'STOCK_DISPOSAL_RECOMMENDED',
  STAFF_BEHAVIOUR_ALERT = 'STAFF_BEHAVIOUR_ALERT',
  DOUBLE_ENTRY_VALIDATION_FAILED = 'DOUBLE_ENTRY_VALIDATION_FAILED',
  TRANSACTION_APPROVAL_TIME_MEASURED = 'TRANSACTION_APPROVAL_TIME_MEASURED',
  SALES_RETURN_REQUESTED = 'SALES_RETURN_REQUESTED',
  SALES_RETURN_COMPLETED = 'SALES_RETURN_COMPLETED',
  MARKET_SPACE_SIGNAL_CAPTURED = 'MARKET_SPACE_SIGNAL_CAPTURED',
}

export type BISeverity = 'info' | 'warning' | 'critical';

export interface BIEventPayload {
  vendorId: string;
  branchId?: string;
  terminalId?: string;
  shiftId?: string;
  userId: string;
  userEmail: string;
  userRole: string;
  eventType: BIEventType;
  entityType?: string;
  entityId?: string;
  severity: BISeverity;
  message: string;
  metadata?: any;
}

export const createBIEvent = async (payload: BIEventPayload) => {
  try {
    const eventId =
      `BI-EVT-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`.toUpperCase();
    const eventRef = doc(db, 'biEvents', eventId);

    await setDoc(eventRef, {
      ...payload,
      eventId,
      reviewed: false,
      reviewedBy: '',
      reviewedAt: null,
      createdAt: serverTimestamp(),
    });

    return eventId;
  } catch (error) {
    console.warn('[BI_EVENT_FAILURE]', error);
    return null;
  }
};
